-- Local development fixtures for Job IQ.
-- These rows give the app a realistic job catalog without creating fake auth users.

insert into public.job_sources (
  id,
  name,
  source_type,
  base_url,
  sync_enabled,
  last_sync_status,
  config
) values (
  '11111111-1111-4111-8111-111111111111',
  'Job IQ Fixture Feed',
  'public_feed',
  'https://example.com/job-iq-fixtures',
  false,
  'fixture',
  '{"environment": "local", "notes": "Static seed data for development"}'::jsonb
) on conflict (name) do update set
  source_type = excluded.source_type,
  base_url = excluded.base_url,
  sync_enabled = excluded.sync_enabled,
  last_sync_status = excluded.last_sync_status,
  config = excluded.config,
  updated_at = now();

-- Jobs are upserted by source/external ID so this file can be rerun safely.
with fixture_source as (
  select id
  from public.job_sources
  where name = 'Job IQ Fixture Feed'
)
insert into public.jobs (
  id,
  source_id,
  external_id,
  dedupe_key,
  title,
  company_name,
  description,
  requirements,
  apply_url,
  location,
  country_code,
  work_mode,
  employment_type,
  salary_min_usd,
  salary_max_usd,
  salary_period,
  seniority,
  industry,
  skills,
  posted_at,
  expires_at,
  is_active,
  raw_payload
)
select
  fixture_job.id,
  fixture_source.id,
  fixture_job.external_id,
  encode(
    digest(
      lower(
        regexp_replace(
          concat_ws(
            '|',
            fixture_source.id::text,
            fixture_job.company_name,
            fixture_job.title,
            fixture_job.location,
            fixture_job.apply_url
          ),
          '\s+',
          ' ',
          'g'
        )
      ),
      'sha256'
    ),
    'hex'
  ),
  fixture_job.title,
  fixture_job.company_name,
  fixture_job.description,
  fixture_job.requirements,
  fixture_job.apply_url,
  fixture_job.location,
  fixture_job.country_code,
  fixture_job.work_mode,
  fixture_job.employment_type,
  fixture_job.salary_min_usd,
  fixture_job.salary_max_usd,
  fixture_job.salary_period,
  fixture_job.seniority,
  fixture_job.industry,
  fixture_job.skills,
  fixture_job.posted_at,
  fixture_job.expires_at,
  fixture_job.is_active,
  fixture_job.raw_payload
from fixture_source
cross join (
  values
    (
      '22222222-2222-4222-8222-222222222201'::uuid,
      'fixture-product-frontend-engineer',
      'Product Frontend Engineer',
      'Northstar Health',
      'Build patient-facing workflows for a health-tech matching platform.',
      'React, TypeScript, accessibility, design systems, and product-minded collaboration.',
      'https://example.com/jobs/product-frontend-engineer',
      'San Francisco, CA',
      'US',
      'hybrid',
      'full_time',
      145000,
      185000,
      'year',
      'mid',
      'Health Technology',
      array['React', 'TypeScript', 'Next.js', 'Accessibility', 'Design Systems']::text[],
      now() - interval '3 days',
      now() + interval '45 days',
      true,
      '{"fixture": true, "source": "seed.sql"}'::jsonb
    ),
    (
      '22222222-2222-4222-8222-222222222202'::uuid,
      'fixture-full-stack-ai-engineer',
      'Full Stack AI Engineer',
      'SignalWorks',
      'Create AI-assisted workflows for operations teams using modern web tooling.',
      'Next.js, Postgres, embeddings, background jobs, and practical product judgment.',
      'https://example.com/jobs/full-stack-ai-engineer',
      'Remote',
      'US',
      'remote',
      'full_time',
      155000,
      205000,
      'year',
      'senior',
      'Artificial Intelligence',
      array['Next.js', 'Postgres', 'Supabase', 'Embeddings', 'TypeScript']::text[],
      now() - interval '1 day',
      now() + interval '60 days',
      true,
      '{"fixture": true, "source": "seed.sql"}'::jsonb
    ),
    (
      '22222222-2222-4222-8222-222222222203'::uuid,
      'fixture-data-platform-engineer',
      'Data Platform Engineer',
      'CivicGrid',
      'Own data pipelines that normalize public-sector and partner datasets.',
      'SQL, data modeling, API ingestion, observability, and reliable batch processing.',
      'https://example.com/jobs/data-platform-engineer',
      'Austin, TX',
      'US',
      'onsite',
      'full_time',
      125000,
      165000,
      'year',
      'mid',
      'Government Technology',
      array['SQL', 'Postgres', 'Data Modeling', 'APIs', 'Observability']::text[],
      now() - interval '5 days',
      now() + interval '30 days',
      true,
      '{"fixture": true, "source": "seed.sql"}'::jsonb
    ),
    (
      '22222222-2222-4222-8222-222222222204'::uuid,
      'fixture-product-designer',
      'Product Designer',
      'BrightHire Labs',
      'Design trustworthy hiring experiences for candidates and recruiting teams.',
      'User research, interaction design, prototyping, accessibility, and design systems.',
      'https://example.com/jobs/product-designer',
      'New York, NY',
      'US',
      'hybrid',
      'full_time',
      120000,
      160000,
      'year',
      'mid',
      'Recruiting Technology',
      array['Product Design', 'Figma', 'User Research', 'Accessibility', 'Design Systems']::text[],
      now() - interval '8 days',
      now() + interval '40 days',
      true,
      '{"fixture": true, "source": "seed.sql"}'::jsonb
    ),
    (
      '22222222-2222-4222-8222-222222222205'::uuid,
      'fixture-backend-engineer-integrations',
      'Backend Engineer, Integrations',
      'Atlas Payroll',
      'Build reliable integrations with payroll, HRIS, and benefits providers.',
      'Node.js, API design, queues, Postgres, testing, and security-minded engineering.',
      'https://example.com/jobs/backend-engineer-integrations',
      'Remote',
      'US',
      'remote',
      'full_time',
      135000,
      175000,
      'year',
      'mid',
      'Fintech',
      array['Node.js', 'API Design', 'Postgres', 'Queues', 'Testing']::text[],
      now() - interval '2 days',
      now() + interval '50 days',
      true,
      '{"fixture": true, "source": "seed.sql"}'::jsonb
    ),
    (
      '22222222-2222-4222-8222-222222222206'::uuid,
      'fixture-inactive-frontend-role',
      'Frontend Engineer, Closed Fixture',
      'Archived Co',
      'Inactive fixture used to confirm active-job filters are working.',
      'React and TypeScript.',
      'https://example.com/jobs/inactive-frontend-role',
      'Remote',
      'US',
      'remote',
      'contract',
      90000,
      110000,
      'year',
      'mid',
      'Software',
      array['React', 'TypeScript']::text[],
      now() - interval '90 days',
      now() - interval '1 day',
      false,
      '{"fixture": true, "source": "seed.sql", "inactive": true}'::jsonb
    )
) as fixture_job (
  id,
  external_id,
  title,
  company_name,
  description,
  requirements,
  apply_url,
  location,
  country_code,
  work_mode,
  employment_type,
  salary_min_usd,
  salary_max_usd,
  salary_period,
  seniority,
  industry,
  skills,
  posted_at,
  expires_at,
  is_active,
  raw_payload
)
on conflict (source_id, external_id) do update set
  dedupe_key = excluded.dedupe_key,
  title = excluded.title,
  company_name = excluded.company_name,
  description = excluded.description,
  requirements = excluded.requirements,
  apply_url = excluded.apply_url,
  location = excluded.location,
  country_code = excluded.country_code,
  work_mode = excluded.work_mode,
  employment_type = excluded.employment_type,
  salary_min_usd = excluded.salary_min_usd,
  salary_max_usd = excluded.salary_max_usd,
  salary_period = excluded.salary_period,
  seniority = excluded.seniority,
  industry = excluded.industry,
  skills = excluded.skills,
  posted_at = excluded.posted_at,
  expires_at = excluded.expires_at,
  is_active = excluded.is_active,
  raw_payload = excluded.raw_payload,
  updated_at = now();
